# Machine-specific root directories.
#
# For a different computing environment, these should be the primary
# paths that need to change.

repo_root: /glade/u/home/rossamower/school/uw/cues_git/sentinel-snowmodel-melt-progression/
data_root: /glade/u/home/rossamower/rmower/pixel/